name: Check orders confirmation

on:
  push:
    branches: [main]
  schedule:
  - cron: "0,15,30,45 * * * 1-5"


jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install     
      - name: Run start
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          DODO_CLIENT_ID: ${{ secrets.DODO_CLIENT_ID }}
          DODO_CLIENT_SECRET: ${{ secrets.DODO_CLIENT_SECRET }}
        run: npm run start:check 
        